name: testing
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.6", "3.7", "3.8", "3.9"]
        poetry-version: ["1.1.5"]
        pip-version: ["20.2.4"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup, Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Update pip ${{ matrix.pip-version }}
        run: python -m pip install --upgrade pip==${{ matrix.pip-version }}
        shell: bash

      - name: Set up Poetry ${{ matrix.poetry-version }}
        run: |
          curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py > get-poetry.py
          python get-poetry.py
          rm get-poetry.py
          source $HOME/.poetry/env
          poetry self update ${{ matrix.poetry-version }}
        shell: bash

      - name: Set up Tox
        run: python -m pip install tox==3.23.0
        shell: bash

      - name: Run Tox on current Python version
        run: tox -e py
        shell: bash

  coverage:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup, Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64
      - name: Update pip
        run: python -m pip install --upgrade pip==20.2.4
        shell: bash

      - name: Set up Python
        run: python -m pip install --upgrade pip==20.2.4
        shell: bash

      - name: Set up Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py > get-poetry.py
          python get-poetry.py
          rm get-poetry.py
          source $HOME/.poetry/env
          poetry self update 1.1.5
        shell: bash

      - name: Set up Tox
        run: python -m pip install tox==3.23.0
        shell: bash

      - name: Coverage
        run: tox -e py39-cov
        shell: bash
